.TH GREET 1 "November 2024" "Version 1.0" "User Commands"
.SH NAME
greet \- a simple greeting utility
.SH SYNOPSIS
.B greet
[\fINAME\fR]
.SH DESCRIPTION
.B greet
prints a greeting message. If a name is provided, it prints "Hello, NAME!". Otherwise, it prints "Hello, world!".
.SH AUTHOR
Serghei Iakovlev
